trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secretFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'internal microsoft'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend'
    backendAzureRmResourceGroupLocation: 'westus2'
    backendAzureRmStorageAccountName: 'terraformiacstorageac'
    backendAzureRmContainerName: 'terraformiacstoragecontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
    allowTelemetryCollection: true